// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/loanem-backend/protos/pb/proto/services/course/v1 (interfaces: CourseServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/server/mock_course_client.go -package=server_mock github.com/loanem-backend/protos/pb/proto/services/course/v1 CourseServiceClient
//

// Package server_mock is a generated GoMock package.
package server_mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/loanem-backend/protos/pb/proto/services/course/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCourseServiceClient is a mock of CourseServiceClient interface.
type MockCourseServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCourseServiceClientMockRecorder
	isgomock struct{}
}

// MockCourseServiceClientMockRecorder is the mock recorder for MockCourseServiceClient.
type MockCourseServiceClientMockRecorder struct {
	mock *MockCourseServiceClient
}

// NewMockCourseServiceClient creates a new mock instance.
func NewMockCourseServiceClient(ctrl *gomock.Controller) *MockCourseServiceClient {
	mock := &MockCourseServiceClient{ctrl: ctrl}
	mock.recorder = &MockCourseServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourseServiceClient) EXPECT() *MockCourseServiceClientMockRecorder {
	return m.recorder
}

// AddCourse mocks base method.
func (m *MockCourseServiceClient) AddCourse(ctx context.Context, in *v1.AddCourseRequest, opts ...grpc.CallOption) (*v1.AddCourseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddCourse", varargs...)
	ret0, _ := ret[0].(*v1.AddCourseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCourse indicates an expected call of AddCourse.
func (mr *MockCourseServiceClientMockRecorder) AddCourse(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCourse", reflect.TypeOf((*MockCourseServiceClient)(nil).AddCourse), varargs...)
}

// GetCourses mocks base method.
func (m *MockCourseServiceClient) GetCourses(ctx context.Context, in *v1.GetCoursesRequest, opts ...grpc.CallOption) (*v1.GetCoursesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCourses", varargs...)
	ret0, _ := ret[0].(*v1.GetCoursesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourses indicates an expected call of GetCourses.
func (mr *MockCourseServiceClientMockRecorder) GetCourses(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourses", reflect.TypeOf((*MockCourseServiceClient)(nil).GetCourses), varargs...)
}

// RemoveCourse mocks base method.
func (m *MockCourseServiceClient) RemoveCourse(ctx context.Context, in *v1.RemoveCourseRequest, opts ...grpc.CallOption) (*v1.RemoveCourseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveCourse", varargs...)
	ret0, _ := ret[0].(*v1.RemoveCourseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveCourse indicates an expected call of RemoveCourse.
func (mr *MockCourseServiceClientMockRecorder) RemoveCourse(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCourse", reflect.TypeOf((*MockCourseServiceClient)(nil).RemoveCourse), varargs...)
}
