// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/loanem-backend/protos/pb/proto/services/auth/v1 (interfaces: AssistantServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/server/mock_assistant_client.go -package=server_mock github.com/loanem-backend/protos/pb/proto/services/auth/v1 AssistantServiceClient
//

// Package server_mock is a generated GoMock package.
package server_mock

import (
	context "context"
	reflect "reflect"

	authv1 "github.com/loanem-backend/protos/pb/proto/services/auth/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockAssistantServiceClient is a mock of AssistantServiceClient interface.
type MockAssistantServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAssistantServiceClientMockRecorder
	isgomock struct{}
}

// MockAssistantServiceClientMockRecorder is the mock recorder for MockAssistantServiceClient.
type MockAssistantServiceClientMockRecorder struct {
	mock *MockAssistantServiceClient
}

// NewMockAssistantServiceClient creates a new mock instance.
func NewMockAssistantServiceClient(ctrl *gomock.Controller) *MockAssistantServiceClient {
	mock := &MockAssistantServiceClient{ctrl: ctrl}
	mock.recorder = &MockAssistantServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssistantServiceClient) EXPECT() *MockAssistantServiceClientMockRecorder {
	return m.recorder
}

// CreateAssistant mocks base method.
func (m *MockAssistantServiceClient) CreateAssistant(ctx context.Context, in *authv1.CreateAssistantRequest, opts ...grpc.CallOption) (*authv1.CreateAssistantResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateAssistant", varargs...)
	ret0, _ := ret[0].(*authv1.CreateAssistantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAssistant indicates an expected call of CreateAssistant.
func (mr *MockAssistantServiceClientMockRecorder) CreateAssistant(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAssistant", reflect.TypeOf((*MockAssistantServiceClient)(nil).CreateAssistant), varargs...)
}

// GetActiveAssistants mocks base method.
func (m *MockAssistantServiceClient) GetActiveAssistants(ctx context.Context, in *authv1.GetActiveAssistantsRequest, opts ...grpc.CallOption) (*authv1.GetActiveAssistantsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetActiveAssistants", varargs...)
	ret0, _ := ret[0].(*authv1.GetActiveAssistantsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveAssistants indicates an expected call of GetActiveAssistants.
func (mr *MockAssistantServiceClientMockRecorder) GetActiveAssistants(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveAssistants", reflect.TypeOf((*MockAssistantServiceClient)(nil).GetActiveAssistants), varargs...)
}

// SetAssistantPassword mocks base method.
func (m *MockAssistantServiceClient) SetAssistantPassword(ctx context.Context, in *authv1.SetAssistantPasswordRequest, opts ...grpc.CallOption) (*authv1.SetAssistantPasswordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetAssistantPassword", varargs...)
	ret0, _ := ret[0].(*authv1.SetAssistantPasswordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAssistantPassword indicates an expected call of SetAssistantPassword.
func (mr *MockAssistantServiceClientMockRecorder) SetAssistantPassword(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAssistantPassword", reflect.TypeOf((*MockAssistantServiceClient)(nil).SetAssistantPassword), varargs...)
}
